spring.application.name=SaludRedNorte

resilience4j.circuitbreaker.instances.waitlistService.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.waitlistService.slidingWindowSize=5
resilience4j.circuitbreaker.instances.waitlistService.failureRateThreshold=50
resilience4j.circuitbreaker.instances.waitlistService.waitDurationInOpenState=10s
resilience4j.circuitbreaker.instances.waitlistService.permittedNumberOfCallsInHalfOpenState=2

spring.datasource.url=jdbc:oracle:thin:@fullstack3_low?TNS_ADMIN=D:/Wallet
spring.datasource.username=ADMIN
spring.datasource.password=Fullstack0326
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true